// app/src/views/HomeView.tsx
import { useEffect } from "react";
import { useAppStore } from "@/stores/app";

/** Landing page: hero + backend health card (port of HomeView.vue). */
export default function HomeView() {
  const health = useAppStore((s) => s.health);
  const healthError = useAppStore((s) => s.healthError);
  const healthLoading = useAppStore((s) => s.healthLoading);
  const checkHealth = useAppStore((s) => s.checkHealth);

  useEffect(() => {
    void checkHealth();
  }, [checkHealth]);

  return (
    <div className="flex flex-col items-center justify-center gap-8 py-16">
      {/* Hero */}
      <div className="text-center space-y-4">
        <h2 className="font-heading text-4xl md:text-6xl text-nd-cyan">
          NEON<span className="text-nd-magenta">//</span>DUSK
        </h2>
        <p className="text-nd-text-secondary text-lg font-body max-w-md mx-auto">
          Build your chrome. Burn your name. Leave a legend.
        </p>
      </div>

      {/* System Status Card */}
      <div className="card w-full max-w-md space-y-3">
        <h3 className="font-heading text-nd-cyan">System Status</h3>

        {healthLoading ? (
          <div className="text-nd-text-secondary font-data text-sm">
            <span className="animate-pulse-neon">▌ Checking connection...</span>
          </div>
        ) : healthError ? (
          <div className="space-y-2">
            <p className="text-nd-magenta font-data text-sm">{healthError}</p>
            <button onClick={() => void checkHealth()} className="btn-neon text-xs">
              Retry
            </button>
          </div>
        ) : health ? (
          <div className="font-data text-sm space-y-2">
            <div className="flex justify-between">
              <span className="text-nd-text-secondary">Status</span>
              <span className={health.status === "ok" ? "text-nd-green" : "text-nd-magenta"}>
                {health.status === "ok" ? "● ONLINE" : "◌ DEGRADED"}
              </span>
            </div>
            <div className="flex justify-between">
              <span className="text-nd-text-secondary">Database</span>
              <span
                className={health.services.database === "connected" ? "text-nd-green" : "text-nd-magenta"}
              >
                {health.services.database}
              </span>
            </div>
            <div className="flex justify-between">
              <span className="text-nd-text-secondary">Redis</span>
              <span
                className={health.services.redis === "connected" ? "text-nd-green" : "text-nd-magenta"}
              >
                {health.services.redis}
              </span>
            </div>
            <div className="flex justify-between">
              <span className="text-nd-text-secondary">Uptime</span>
              <span className="text-nd-gold">{Math.floor(health.uptime)}s</span>
            </div>
            <div className="flex justify-between">
              <span className="text-nd-text-secondary">Version</span>
              <span className="text-nd-gold">{health.version}</span>
            </div>
          </div>
        ) : null}
      </div>
    </div>
  );
}

// app/src/views/HomeView.vue
<script setup lang="ts">
import { onMounted } from "vue";
import { useAppStore } from "@/stores/app";

const store = useAppStore();

onMounted(() => {
  store.checkHealth();
});
</script>

<template>
  <div class="flex flex-col items-center justify-center gap-8 py-16">
    <!-- Hero -->
    <div class="text-center space-y-4">
      <h2 class="font-heading text-4xl md:text-6xl text-nd-cyan">
        NEON<span class="text-nd-magenta">//</span>DUSK
      </h2>
      <p class="text-nd-text-secondary text-lg font-body max-w-md mx-auto">
        Build your chrome. Burn your name. Leave a legend.
      </p>
    </div>

    <!-- System Status Card -->
    <div class="card w-full max-w-md space-y-3">
      <h3 class="font-heading text-nd-cyan">System Status</h3>

      <div v-if="store.healthLoading" class="text-nd-text-secondary font-data text-sm">
        <span class="animate-pulse-neon">▌ Checking connection...</span>
      </div>

      <div v-else-if="store.healthError" class="space-y-2">
        <p class="text-nd-magenta font-data text-sm">{{ store.healthError }}</p>
        <button @click="store.checkHealth()" class="btn-neon text-xs">Retry</button>
      </div>

      <div v-else-if="store.health" class="font-data text-sm space-y-2">
        <div class="flex justify-between">
          <span class="text-nd-text-secondary">Status</span>
          <span :class="store.isHealthy ? 'text-nd-green' : 'text-nd-magenta'">
            {{ store.isHealthy ? "● ONLINE" : "◌ DEGRADED" }}
          </span>
        </div>
        <div class="flex justify-between">
          <span class="text-nd-text-secondary">Database</span>
          <span :class="store.dbConnected ? 'text-nd-green' : 'text-nd-magenta'">
            {{ store.health.services.database }}
          </span>
        </div>
        <div class="flex justify-between">
          <span class="text-nd-text-secondary">Redis</span>
          <span :class="store.redisConnected ? 'text-nd-green' : 'text-nd-magenta'">
            {{ store.health.services.redis }}
          </span>
        </div>
        <div class="flex justify-between">
          <span class="text-nd-text-secondary">Uptime</span>
          <span class="text-nd-gold">{{ Math.floor(store.health.uptime) }}s</span>
        </div>
        <div class="flex justify-between">
          <span class="text-nd-text-secondary">Version</span>
          <span class="text-nd-gold">{{ store.health.version }}</span>
        </div>
      </div>
    </div>
  </div>
</template>
