// app/src/components/StatusBar.tsx
import { useEffect } from "react";
import { useAppStore } from "@/stores/app";

/**
 * Backend health indicator. Polls /api/health on mount and shows one of
 * four states: connecting, offline (click to retry), online, degraded
 * (port of StatusBar.vue).
 */
export default function StatusBar() {
  const healthLoading = useAppStore((s) => s.healthLoading);
  const healthError = useAppStore((s) => s.healthError);
  const health = useAppStore((s) => s.health);
  const checkHealth = useAppStore((s) => s.checkHealth);

  useEffect(() => {
    void checkHealth();
  }, [checkHealth]);

  return (
    <div className="flex items-center gap-2 text-xs font-data">
      {healthLoading ? (
        <span className="text-nd-text-secondary animate-pulse-neon">▌ connecting...</span>
      ) : healthError ? (
        <span
          className="text-nd-magenta cursor-pointer"
          title="Click to retry"
          onClick={() => void checkHealth()}
        >
          ◌ offline
        </span>
      ) : health?.status === "ok" ? (
        <span className="text-nd-green"> ● online </span>
      ) : (
        <span className="text-nd-gold"> ◌ degraded </span>
      )}
    </div>
  );
}

// app/src/components/StatusBar.vue
<script setup lang="ts">
import { onMounted } from "vue";
import { useAppStore } from "@/stores/app";

const store = useAppStore();

onMounted(() => {
  store.checkHealth();
});
</script>

<template>
  <div class="flex items-center gap-2 text-xs font-data">
    <!-- Loading -->
    <span v-if="store.healthLoading" class="text-nd-text-secondary animate-pulse-neon">
      ▌ connecting...
    </span>

    <!-- Error -->
    <span
      v-else-if="store.healthError"
      class="text-nd-magenta cursor-pointer"
      title="Click to retry"
      @click="store.checkHealth()"
    >
      ◌ offline
    </span>

    <!-- Healthy -->
    <span v-else-if="store.isHealthy" class="text-nd-green"> ● online </span>

    <!-- Degraded -->
    <span v-else class="text-nd-gold"> ◌ degraded </span>
  </div>
</template>
