// app/src/App.tsx
import { Outlet } from "react-router-dom";
import AppHeader from "@/components/AppHeader";
import AppFooter from "@/components/AppFooter";

/** App shell: header + routed content + footer (port of App.vue). */
export default function App() {
  return (
    <div className="min-h-screen bg-nd-bg flex flex-col">
      <AppHeader />
      <main className="flex-1">
        <Outlet />
      </main>
      <AppFooter />
    </div>
  );
}

// app/src/App.vue
<script setup lang="ts">
import AppHeader from "./components/AppHeader.vue";
import AppFooter from "./components/AppFooter.vue";
</script>

<template>
  <div class="min-h-screen bg-nd-bg flex flex-col">
    <AppHeader />
    <main class="flex-1 max-w-6xl mx-auto w-full px-4 py-6">
      <router-view />
    </main>
    <AppFooter />
  </div>
</template>
